config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  get 'formresource/show'

  get 'formtest/show'

  get 'showtime/showit'

  get 'temp/index'
  
  get '/temp/docalc'
  
  get 'formtest', to: 'formtest#show'
  
  resources :photos
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/temp.rb
class Temp < ApplicationRecord
    
    def self.ConvertTemp(temp,type)
	 
	    tempnum=temp.to_i
	    
		if type.eql?'celsius'
		
		  tt=tempnum*9/5+32
		
		else
		
		  tt=(tempnum-32)*5/9
		
		end
	 
	 
	 end
    
end

app/models/temp_calc.rb
class TempCalc < ApplicationRecord
 
   
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/formresource_controller.rb
class FormresourceController < ApplicationController
  def show
  end
end

app/controllers/formtest_controller.rb
class FormtestController < ApplicationController
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
def index

end

def show
@photo=Photo.new()
end
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :content)
    end
end

app/controllers/showtime_controller.rb
class ShowtimeController < ApplicationController
    def showit
        
    end
end

app/controllers/temp_controller.rb
class TempController < ApplicationController
    
    def index1
   
    respond_to do |format|
      format.html # index.html.erb
      
    end
  end
    
    def docalc
  
      temp=params[:temp]
	  type=params[:type]
  
	  convertedTemp= Temp.ConvertTemp(temp,type)
      notice_string='docalc: temperature '+ params[:temp] +' in '+ \
      params[:type].to_s+ ' is '+ convertedTemp.to_s
	 
      respond_to  do |format|
          
		  format.html { redirect_to '/temp/index', notice: notice_string}		  
     
       end

  
    end
    
    def show
  
      temp=params[:temp]
	  type=params[:type]
  
	  convertedTemp=Temp.ConvertTemp(temp,type)
      notice_string='temperature '+ params[:temp] +' in '+ params[:type].to_s+ ' is '+ convertedTemp.to_s
	  
	
      respond_to  do |format|
          
		  format.html { redirect_to '/temp/index', notice: notice_string}		  
     
       end
  
  end
    
    private
  
     def ConvertTemp(temp,type)
	 
	    tempnum=temp.to_i
	    
		if type.eql?'celsius'
		
		  tt=tempnum*9/5+32
		
		else
		
		  tt=(tempnum-32)*5/9
		
		end
	 
	 
	 end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formresource_helper.rb
module FormresourceHelper
end

app/helpers/formtest_helper.rb
module FormtestHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/showtime_helper.rb
module ShowtimeHelper
end

app/helpers/temp_helper.rb
module TempHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/formresource/show.html.erb
<h1>Formresource#show</h1>
<p>Find me in app/views/formresource/show.html.erb</p>

app/views/formtest/show.html.erb
<h1>Formtest#show</h1>
<p>Find me in app/views/formtest/show.html.erb</p>
<%= form_tag do %>
  some stuff
<% end %>


<%= form_tag("formtest/show", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/photos/index.html.erb
<h> list photo index </h>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.content %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @recipe.content %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>


<%= form_for(@recipe) do |f|   end %>

app/views/showtime/showit.html.erb
<h1>Showtime#showit</h1>
<p> Find me in app/views/showtime/showit.html.erb</p>

<p> current time is <%= Time.now %>  </p>

app/views/temp/index.html.erb
<h1>Temerature Convertor</h1>
<p id="notice"><%= notice %></p>

<%=form_tag("/temp/docalc", :method => "get") do %>
<%= radio_button_tag(:type, "celsius") %>
<%= label_tag(:celsius, "celsius") %>
<%= radio_button_tag(:type, "fahrenhelt") %>
<%= label_tag(:fahrenhelt, "fahrenhelt") %>
<br> </br>
<%= label_tag(:temp, "input temperature") %>
<%= text_field_tag(:temp) %>
<%= submit_tag("Search") %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>